try {
    (async () => {
        //
    })();
} catch (e) {
    console.log("cert :: error", e);
}