try {
    (async () => {
        
    })();
} catch (error) {
    console.error("cert :: error", error);
}